version: "3"
services:
  openhab:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - USER_ID=999
      - GROUP_ID=998
  theia:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - USER_ID=999
      - GROUP_ID=998
    user: 999:998
  nodered:
    environment:
      - USER_ID=999
      - GROUP_ID=998
  mqtt:
    user: 999:998
